### ISSUE TITLE
Issue with jumping menus on Ubuntu 16.04

### ISSUE THREAD

**Issue by theopensourcerer** [slgobinath/libreoffice-code-highlighter#11]
I just installed this extension and when I enable it the menus of all open windows (apart from apps which draw their own - like Chrome/Firefox) "jump" up and down on the screen making it unusable.

I tried setting the Menus to be shown in the Menu bar (global menus) as well as how I like it which is in the Title bar of each window. The symptom persists.

See this screeencast to see the effect. https://goo.gl/photos/JN3VeAKxYKThcNp68

**Comment by slgobinath** [comment]
That;s horrible. I think it is due to a large number of menu items. Thanks for the detailed bug report. I will try my best to eliminate it.

**Comment by slgobinath** [comment]
Hi @theopensourcerer,

I have tested this problem on Ubuntu 14.04 and 16.04. The bug occurs only on Ubuntu 16.04. After some testing, I found the bug is somewhat related to LO 5.2.x. Upgrading LO to 5.4 resolved the problem in my testing environment. To upgrade LO to 5.4, follow these steps taken from [Omg Ubuntu](http://www.omgubuntu.co.uk/2017/07/how-to-install-libreoffice-5-4-on-ubuntu):
1. Add the official LibreOffice PPA
```
sudo add-apt-repository ppa:libreoffice/libreoffice-5-4
```

2. Upgrade LibreOffice
```
sudo apt update && sudo apt install libreoffice
```

If this solution works, please do let me know.

Thanks

**Comment by theopensourcerer** [comment]
Thanks for the follow up. I ended up using a cli script to create an RTF from a diff and then adding these to my document so the urgency is off for the moment. 

It's good to hear that there is an easy workaround. I will update LibreOffice when I get chance and confirm if any issues but please, in the meantime, close this if you wish.

Thanks again

**Comment by theopensourcerer** [comment]
I am going to close this. It's nothing to do with the extension. It just started happening on my laptop (16.04 without the extension installed). I upgraded to LibreOffice 5.4 and all is sane with the world again :-)
