### ISSUE TITLE
Which file is the real script?

### ISSUE THREAD

**Issue by rbrito** [slgobinath/libreoffice-code-highlighter#18]
This repository has two files that seem to be the intended script:

* https://github.com/slgobinath/libreoffice-code-highlighter/blob/master/Highlight.py
* https://github.com/slgobinath/libreoffice-code-highlighter/blob/master/codehighlighter/python/highlight.py

Which one is the right one? If one takes into account the last modified date, then it seems that the second one is the right file. But being at the top level of the project makes people believe that it should be the first.

Can you remove the unintended file from the repository? Of course, it will be still in the history of the project, for those that want to see how the project came to be.

**Comment by slgobinath** [comment]
Thanks for pointing this out. I did not notice that file until now ^_^. I already created a separate [branch](https://github.com/slgobinath/libreoffice-code-highlighter/tree/code-highlighter-old) to keep the old script.

Fixed with https://github.com/slgobinath/libreoffice-code-highlighter/commit/fec1fdb0c598231492a440c7ec04214b608e0682
